#!/bin/sh
red="\e[0;31m"
cyan="\e[1;36m"
blue="\e[0;94m"
green="\e[0;32m"
purple="\e[0;35m"

function get_colour()
{
if [ -d /etc/dpkg ]; then
	pkgs=$[$(dpkg -l |wc -l)-6]
	pkgmgr="dpkg"
	colour="$red"

elif [ -e /etc/pacman.conf ]; then
	pkgs="$(pacman -Qq |wc -l)"
	pkgmgr="pacman"
	colour="$cyan"

elif [ -d /etc/apk ]; then
	pkgs="$(apk info |wc -l)"
	pkgmgr="apk"
	colour="$blue"

elif [ -d /etc/dnf ]; then
	pkgs=$[$(dnf list installed |wc -l)-2]
	pkgmgr="dnf"
	colour="$blue"

elif [ -d /etc/yum ]; then
	pkgs=$[$(yum list installed -q| wc -l)-1]
	pkgmgr="yum"
	colour"$green"

elif [ -e /etc/xbps.d ]; then
	pkgs="$(xbps-query -l | wc -l)"
	pkgmgr="xbps"
	colour"$green"
fi
}

function get_username()
{
	username="$(whoami)"
	echo "$username"
}

function get_hostname()
{
	hostname="$(hostnamectl hostname)"
	echo "$hostname"
}

function get_os()
{
	os="$(grep "^PRETTY_NAME" /etc/os-release |cut -d"=" -f2| cut -d'"' -f2) $(uname -m)"
	echo "$os"
}

function get_kernel()
{
	kernel="$(uname -r)"
	echo "$kernel"
}

function get_shell()
{
	shell="$(echo $SHELL)"
	echo "$shell"
}

function get_uptime()
{
	uptime="$(uptime -p | sed 's/up //g')"
	echo "$uptime"
}

function get_ram()
{
	ram="$(free -h | grep Mem | awk '{print $3 " / " $2}' | sed 's/Gi/gb/g' | sed 's/Mi/mb/g')"
	echo "$ram"
}

function get_home()
{
	home="$(df -h /home | grep / | awk '{print $3"/"$4 " ("$5") used"}')"
	echo "$home"
}

function get_all()
{
	reset="\e[0m"
	get_colour
	echo -e ""$colour$(get_username)$reset"@"$colour$(get_hostname)$reset
	echo -e ""$colour"os\t\t"$reset $(get_os)
	echo -e ""$colour"kernel\t\t"$reset $(get_kernel)
	echo -e ""$colour"shell\t\t"$reset $(get_shell)
	echo -e ""$colour"uptime\t\t"$reset $(get_uptime)
	echo -e ""$colour"packages\t"$reset "$pkgs" "($pkgmgr)"
	echo -e ""$colour"ram\t\t"$reset $(get_ram)
	echo -e ""$colour"home part\t"$reset $(get_home)"\n"

}

function print_help()
{
	echo -e "syntax: sysfetch [option] [option]..."
	echo -e "help\t\t prints this help message"
	echo -e "username\t user's username"
	echo -e "hostname\t machine's hostname"
	echo -e "os\t\t operating system"
	echo -e "shell\t\t default shell"
	echo -e "uptime\t\t machine's uptime"
	echo -e "pkgs\t\t number of packages installed"
	echo -e "ram\t\t ram usage"
	echo -e "home\t\t home partition usage"
}

if [ "$#" == "0" ]; then
	get_all
else
	for i in "$@"; do
		case "$i" in
			"help") print_help ;;
			"username") get_username ;;
			"hostname") get_hostname ;;
			"os") get_os ;;
			"kernel") get_kernel ;;
			"uptime") get_uptime ;;
			"shell") get_shell ;;
			"pkgs") get_packages ;;
			"ram") get_ram ;;
			"home") get_home ;;
			*) print_help ;;
		esac
	done
fi
